version: "3.6"

services:
  indexer:
    image: dipdup/metadata:latest
    command: -c dipdup.search.yml
    build:
        dockerfile: build/metadata/Dockerfile
        context: .
    env_file:
      - .env
    depends_on:
      - elastic
    restart: always

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    restart: always
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
    env_file:
      - .env
    ports:
      - 127.0.0.1:9200:9200

  api:
    image: dipdup/metadata-api:latest
    command: -c dipdup.search.yml
    build:
        dockerfile: build/api/Dockerfile
        context: .
    env_file:
      - .env
    depends_on:
      - elastic
    restart: always
    ports:
      - 127.0.0.1:11111:11111

volumes:
  esdata:
